name: Routine README.md Updater

on:
  schedule:
    # Every 12 hours!
    - cron: "0 */12 * * *"
  push:
    branches:
      - main

jobs:
  Updater:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.USER_TOKEN }}
          includeForks: true

      - name: Update README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Update README.md"
          git push
          fi
